### ISSUE TITLE
Add linting requirement to CI

### ISSUE THREAD

**Issue by jonathf** [jonathf/pyvroom#12]
Likely pylint, but might choose something else.

**Comment by nilsnolde** [comment]
fwiw, I found flake8 & black a nice combo. only annoyance is that flake8 doesn't support pyproject.toml (last I checked) and black doesn't support setup.cfg. since you already have both that's less of a problem though. most important part is to sync the `max-line-length`. I'll leave my general config here, maybe it helps a little:

setup.cfg (I had a version where I inlined comments what the `ignore`s represent but can't find it atm)
```
[flake8]
# ignore some errors to play nicely with black
ignore = E203,E266,E501,W503,F403,E722,F405
max-complexity = 15
max-line-length = 105
exclude = .venv,.git,__pycache__,docs,dist,examples
```

pyproject.toml
```
[tool.black]
line-length = 105
exclude = '''
/(
    \.git
  | \.venv
  | dist
  | build
)/
'''
```

**Comment by jonathf** [comment]
Thanks for that. I was trying to get away from pylint as I think has become to slow lately.

Added flake8 checks to the circleci piepline now.
